In [2]:
import numpy as np

### Scratch Work

In [28]:
t = np.array([(1, 2), (4, 0)])
np.append(np.zeros(4*2), np.random.rand(1))

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.56111315])

In [45]:
np.expand_dims((1, 2), axis=0)

array([[1, 2]])

In [56]:
w = np.random.rand(3, 2)
fa = np.repeat(np.expand_dims((1, 2), axis=0), 3, axis = 0)

(w * fa).sum(axis = 1)

array([1.03615528, 1.30740881, 0.39351483])

In [57]:
((1, 2),)

((1, 2),)

In [23]:
a, b = [0, (1, 2)]

b

(1, 2)

In [57]:
a = np.random.randn(5, 4, 2)
w = np.array([0, 1])

a

array([[[-0.17492921, -0.33713424],
        [-0.25750947,  0.69885757],
        [ 0.2882379 , -0.04518748],
        [ 0.14827089,  0.39415077]],

       [[-0.04453902,  0.02460233],
        [ 0.42080711, -0.50323193],
        [-0.39822003,  0.29811923],
        [ 1.17323085,  0.4813951 ]],

       [[-0.43380372,  0.09008668],
        [ 0.13771389, -0.17200919],
        [-0.05806451,  0.6026589 ],
        [-2.58707392,  0.04315591]],

       [[-0.23278396, -1.86398221],
        [ 0.13669692, -0.59046992],
        [-1.12918463,  0.28976368],
        [ 0.34748918, -0.37808657]],

       [[ 1.8141762 ,  0.17034818],
        [-1.38171228,  1.09214063],
        [ 0.7372182 ,  0.29960152],
        [-1.01641124, -0.29459543]]])

In [39]:
np.concatenate(([4], [5], [3]))

array([4, 5, 3])

In [64]:
(1, [2, 3])

TypeError: tuple expected at most 1 argument, got 2

In [69]:
from itertools import chain

ab = chain('it', ['was'], ['annoying'])
list(ab)

['i', 't', 'was', 'annoying']

In [54]:

r = np.array([0, 1]) + np.array([[0, 1], [1, 1]])
r.astype(int)

array([[0, 2],
       [1, 2]])

In [20]:
s = a[0]
np.sum(np.expand_dims(w, axis = 0) * s, axis = 1)

array([ 0.41440023,  1.45997854,  1.32371718, -0.3735584 ])

In [15]:

np.sum(np.expand_dims(w, axis = 0) * s, axis = 1)

array([ 0.41440023,  1.45997854,  1.32371718, -0.3735584 ])

In [19]:
q_state = np.sum(np.expand_dims(w, axis = -1) * a[:, 0, :], axis = 0)

In [20]:
np.all(q_state) == q_state[0]

False

In [31]:
delta = (
            [2, 1]
            + .1 * np.max(a[:, 0, :])
            - a[:, 1, 1]
        )

In [35]:
a[:, 0, 1] + delta

array([4.98506006, 1.39523359])